In [5]:
import numpy

In [ ]:
numpy.loadtxt(fname="data/inflammation-01.csv",delimiter=',')

In [6]:
ar= numpy.loadtxt(fname="data/inflammation-01.csv",delimiter=',')

In [7]:
print("a:",ar[0][0])

a: 0.0


In [8]:
co = ar[:3, 36:]
print(co)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


#EX

#ffg

In [10]:
print(ar.max(axis=1).shape)


(60,)


In [11]:
print(ar.max(axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [12]:
print(ar.max(axis=0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]
